name: agendamiento_canchas
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"




dependencies:
  flutter:
    sdk: flutter

     

  cupertino_icons: ^1.0.0
  sqflite: ^1.3.0
  http: ^0.12.2
  flutter_screenutil: ^1.0.2
  intl: ^0.16.1
  provider: ^4.0.5+1
  fluttertoast: ^7.0.4




dev_dependencies:
  test: ^1.15.4
  mockito:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
   - assets/
